/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AdminloginRouteImport } from './routes/adminlogin'
import { Route as AiHelpRouteImport } from './routes/ai-help'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ElectivesRouteImport } from './routes/electives'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProgramSelectionRouteImport } from './routes/program-selection'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SemesterSelectionRouteImport } from './routes/semester-selection'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiStudyAudioRouteImport } from './routes/api/study-audio'
import { Route as ApiStudyHelpRouteImport } from './routes/api/study-help'
import { Route as ModelPaperPaperIdRouteImport } from './routes/model-paper.$paperId'
import { Route as ModelPapersSubjectIdRouteImport } from './routes/model-papers.$subjectId'
import { Route as SubjectSubjectIdRouteImport } from './routes/subject.$subjectId'
import { Route as UnitUnitIdRouteImport } from './routes/unit.$unitId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminloginRoute = AdminloginRouteImport.update({
  id: '/adminlogin',
  path: '/adminlogin',
  getParentRoute: () => rootRouteImport,
} as any)
const AiHelpRoute = AiHelpRouteImport.update({
  id: '/ai-help',
  path: '/ai-help',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ElectivesRoute = ElectivesRouteImport.update({
  id: '/electives',
  path: '/electives',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramSelectionRoute = ProgramSelectionRouteImport.update({
  id: '/program-selection',
  path: '/program-selection',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SemesterSelectionRoute = SemesterSelectionRouteImport.update({
  id: '/semester-selection',
  path: '/semester-selection',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiStudyAudioRoute = ApiStudyAudioRouteImport.update({
  id: '/api/study-audio',
  path: '/api/study-audio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStudyHelpRoute = ApiStudyHelpRouteImport.update({
  id: '/api/study-help',
  path: '/api/study-help',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelPaperPaperIdRoute = ModelPaperPaperIdRouteImport.update({
  id: '/model-paper/$paperId',
  path: '/model-paper/$paperId',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelPapersSubjectIdRoute = ModelPapersSubjectIdRouteImport.update({
  id: '/model-papers/$subjectId',
  path: '/model-papers/$subjectId',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectSubjectIdRoute = SubjectSubjectIdRouteImport.update({
  id: '/subject/$subjectId',
  path: '/subject/$subjectId',
  getParentRoute: () => rootRouteImport,
} as any)
const UnitUnitIdRoute = UnitUnitIdRouteImport.update({
  id: '/unit/$unitId',
  path: '/unit/$unitId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adminlogin': typeof AdminloginRoute
  '/ai-help': typeof AiHelpRoute
  '/auth': typeof AuthRoute
  '/bookmarks': typeof BookmarksRoute
  '/dashboard': typeof DashboardRoute
  '/electives': typeof ElectivesRoute
  '/landing': typeof LandingRoute
  '/notifications': typeof NotificationsRoute
  '/payment': typeof PaymentRoute
  '/premium': typeof PremiumRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/program-selection': typeof ProgramSelectionRoute
  '/refund': typeof RefundRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/semester-selection': typeof SemesterSelectionRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/api/study-audio': typeof ApiStudyAudioRoute
  '/api/study-help': typeof ApiStudyHelpRoute
  '/model-paper/$paperId': typeof ModelPaperPaperIdRoute
  '/model-papers/$subjectId': typeof ModelPapersSubjectIdRoute
  '/subject/$subjectId': typeof SubjectSubjectIdRoute
  '/unit/$unitId': typeof UnitUnitIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adminlogin': typeof AdminloginRoute
  '/ai-help': typeof AiHelpRoute
  '/auth': typeof AuthRoute
  '/bookmarks': typeof BookmarksRoute
  '/dashboard': typeof DashboardRoute
  '/electives': typeof ElectivesRoute
  '/landing': typeof LandingRoute
  '/notifications': typeof NotificationsRoute
  '/payment': typeof PaymentRoute
  '/premium': typeof PremiumRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/program-selection': typeof ProgramSelectionRoute
  '/refund': typeof RefundRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/semester-selection': typeof SemesterSelectionRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/api/study-audio': typeof ApiStudyAudioRoute
  '/api/study-help': typeof ApiStudyHelpRoute
  '/model-paper/$paperId': typeof ModelPaperPaperIdRoute
  '/model-papers/$subjectId': typeof ModelPapersSubjectIdRoute
  '/subject/$subjectId': typeof SubjectSubjectIdRoute
  '/unit/$unitId': typeof UnitUnitIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/adminlogin': typeof AdminloginRoute
  '/ai-help': typeof AiHelpRoute
  '/auth': typeof AuthRoute
  '/bookmarks': typeof BookmarksRoute
  '/dashboard': typeof DashboardRoute
  '/electives': typeof ElectivesRoute
  '/landing': typeof LandingRoute
  '/notifications': typeof NotificationsRoute
  '/payment': typeof PaymentRoute
  '/premium': typeof PremiumRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/program-selection': typeof ProgramSelectionRoute
  '/refund': typeof RefundRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/semester-selection': typeof SemesterSelectionRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/api/study-audio': typeof ApiStudyAudioRoute
  '/api/study-help': typeof ApiStudyHelpRoute
  '/model-paper/$paperId': typeof ModelPaperPaperIdRoute
  '/model-papers/$subjectId': typeof ModelPapersSubjectIdRoute
  '/subject/$subjectId': typeof SubjectSubjectIdRoute
  '/unit/$unitId': typeof UnitUnitIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adminlogin'
    | '/ai-help'
    | '/auth'
    | '/bookmarks'
    | '/dashboard'
    | '/electives'
    | '/landing'
    | '/notifications'
    | '/payment'
    | '/premium'
    | '/privacy'
    | '/profile'
    | '/program-selection'
    | '/refund'
    | '/reset-password'
    | '/search'
    | '/semester-selection'
    | '/settings'
    | '/terms'
    | '/admin'
    | '/api/study-audio'
    | '/api/study-help'
    | '/model-paper/$paperId'
    | '/model-papers/$subjectId'
    | '/subject/$subjectId'
    | '/unit/$unitId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adminlogin'
    | '/ai-help'
    | '/auth'
    | '/bookmarks'
    | '/dashboard'
    | '/electives'
    | '/landing'
    | '/notifications'
    | '/payment'
    | '/premium'
    | '/privacy'
    | '/profile'
    | '/program-selection'
    | '/refund'
    | '/reset-password'
    | '/search'
    | '/semester-selection'
    | '/settings'
    | '/terms'
    | '/admin'
    | '/api/study-audio'
    | '/api/study-help'
    | '/model-paper/$paperId'
    | '/model-papers/$subjectId'
    | '/subject/$subjectId'
    | '/unit/$unitId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/adminlogin'
    | '/ai-help'
    | '/auth'
    | '/bookmarks'
    | '/dashboard'
    | '/electives'
    | '/landing'
    | '/notifications'
    | '/payment'
    | '/premium'
    | '/privacy'
    | '/profile'
    | '/program-selection'
    | '/refund'
    | '/reset-password'
    | '/search'
    | '/semester-selection'
    | '/settings'
    | '/terms'
    | '/_authenticated/admin'
    | '/api/study-audio'
    | '/api/study-help'
    | '/model-paper/$paperId'
    | '/model-papers/$subjectId'
    | '/subject/$subjectId'
    | '/unit/$unitId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminloginRoute: typeof AdminloginRoute
  AiHelpRoute: typeof AiHelpRoute
  AuthRoute: typeof AuthRoute
  BookmarksRoute: typeof BookmarksRoute
  DashboardRoute: typeof DashboardRoute
  ElectivesRoute: typeof ElectivesRoute
  LandingRoute: typeof LandingRoute
  NotificationsRoute: typeof NotificationsRoute
  PaymentRoute: typeof PaymentRoute
  PremiumRoute: typeof PremiumRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ProgramSelectionRoute: typeof ProgramSelectionRoute
  RefundRoute: typeof RefundRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  SemesterSelectionRoute: typeof SemesterSelectionRoute
  SettingsRoute: typeof SettingsRoute
  TermsRoute: typeof TermsRoute
  ApiStudyAudioRoute: typeof ApiStudyAudioRoute
  ApiStudyHelpRoute: typeof ApiStudyHelpRoute
  ModelPaperPaperIdRoute: typeof ModelPaperPaperIdRoute
  ModelPapersSubjectIdRoute: typeof ModelPapersSubjectIdRoute
  SubjectSubjectIdRoute: typeof SubjectSubjectIdRoute
  UnitUnitIdRoute: typeof UnitUnitIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adminlogin': {
      id: '/adminlogin'
      path: '/adminlogin'
      fullPath: '/adminlogin'
      preLoaderRoute: typeof AdminloginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-help': {
      id: '/ai-help'
      path: '/ai-help'
      fullPath: '/ai-help'
      preLoaderRoute: typeof AiHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/electives': {
      id: '/electives'
      path: '/electives'
      fullPath: '/electives'
      preLoaderRoute: typeof ElectivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program-selection': {
      id: '/program-selection'
      path: '/program-selection'
      fullPath: '/program-selection'
      preLoaderRoute: typeof ProgramSelectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/semester-selection': {
      id: '/semester-selection'
      path: '/semester-selection'
      fullPath: '/semester-selection'
      preLoaderRoute: typeof SemesterSelectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/study-audio': {
      id: '/api/study-audio'
      path: '/api/study-audio'
      fullPath: '/api/study-audio'
      preLoaderRoute: typeof ApiStudyAudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/study-help': {
      id: '/api/study-help'
      path: '/api/study-help'
      fullPath: '/api/study-help'
      preLoaderRoute: typeof ApiStudyHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model-paper/$paperId': {
      id: '/model-paper/$paperId'
      path: '/model-paper/$paperId'
      fullPath: '/model-paper/$paperId'
      preLoaderRoute: typeof ModelPaperPaperIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model-papers/$subjectId': {
      id: '/model-papers/$subjectId'
      path: '/model-papers/$subjectId'
      fullPath: '/model-papers/$subjectId'
      preLoaderRoute: typeof ModelPapersSubjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subject/$subjectId': {
      id: '/subject/$subjectId'
      path: '/subject/$subjectId'
      fullPath: '/subject/$subjectId'
      preLoaderRoute: typeof SubjectSubjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unit/$unitId': {
      id: '/unit/$unitId'
      path: '/unit/$unitId'
      fullPath: '/unit/$unitId'
      preLoaderRoute: typeof UnitUnitIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminloginRoute: AdminloginRoute,
  AiHelpRoute: AiHelpRoute,
  AuthRoute: AuthRoute,
  BookmarksRoute: BookmarksRoute,
  DashboardRoute: DashboardRoute,
  ElectivesRoute: ElectivesRoute,
  LandingRoute: LandingRoute,
  NotificationsRoute: NotificationsRoute,
  PaymentRoute: PaymentRoute,
  PremiumRoute: PremiumRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ProgramSelectionRoute: ProgramSelectionRoute,
  RefundRoute: RefundRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  SemesterSelectionRoute: SemesterSelectionRoute,
  SettingsRoute: SettingsRoute,
  TermsRoute: TermsRoute,
  ApiStudyAudioRoute: ApiStudyAudioRoute,
  ApiStudyHelpRoute: ApiStudyHelpRoute,
  ModelPaperPaperIdRoute: ModelPaperPaperIdRoute,
  ModelPapersSubjectIdRoute: ModelPapersSubjectIdRoute,
  SubjectSubjectIdRoute: SubjectSubjectIdRoute,
  UnitUnitIdRoute: UnitUnitIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
